platform :ios, '15.0'
use_frameworks! :linkage => :static
#use_modular_headers!
inhibit_all_warnings!
install! 'cocoapods',
  :warn_for_unused_master_specs_repo => false,
  :preserve_pod_file_structure => true

source 'git@github.com:igovee/GHSpecs.git'
source 'https://cdn.cocoapods.org'

target 'GHFirebase_Example' do

  pod 'GHFirebase', :path => '../'
  
  pod 'FirebaseAnalytics/Core', '12.11.0'
  pod 'Firebase/Crashlytics', '12.11.0'
  pod 'Firebase/Performance', '12.11.0'
  pod 'Firebase/Auth', '12.11.0'
  
end

post_install do |installer|
 search_modules(installer)
end

def search_modules(installer)
 modules = installer.pod_targets.map do |target|
   module_name = target.info_plist_entries["GHModular"]
 end
 modules.compact!
 #puts modules

 project_path = installer.aggregate_targets[0].user_project_path
 #puts "#{project_path}"
 project = Xcodeproj::Project.open(project_path)
 project_dir_path = project.project_dir
 target = project.targets[0]
 config = target.build_configurations[0]
 settings = config.build_settings
 info_plist_name = settings["INFOPLIST_FILE"]
 info_plist_path = "#{project_dir_path}/#{info_plist_name}"
 puts info_plist_path
 info_plist = Xcodeproj::Plist.read_from_path(info_plist_path)
 info_plist["GHModules"] = modules
 #puts info_plist
 Xcodeproj::Plist.write_to_path(info_plist, info_plist_path)
end
